### ISSUE TITLE
value-keyword-case error on font variables

### ISSUE THREAD

**Issue by pimskie** [vicompany/stylelint-config-vi#3]
Due to the rule `'value-keyword-case': 'lower'` ([docs](http://stylelint.io/user-guide/rules/value-keyword-case/)) values should be in lowercase. 

This raises an error on for example:

``` scss
$typeface-display: 'NHaasGroteskMd', 'Helvetica Neue', Helvetica, Arial, sans-serif;
```

Possible related issue: https://github.com/stylelint/stylelint/issues/1101

**Comment by ba55ie** [comment]
Well it works as intended, see https://github.com/stylelint/stylelint/issues/1588

You have to add the values to the `ignoreValues: []` option or add the comment `/* stylelint-disable-line value-keyword-case */`

http://stylelint.io/user-guide/rules/value-keyword-case/
